package br.com.novaroma.ReverseApp;

/**
 * ReverseApp/ReverseOperations.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from ReverseIDL.idl Domingo, 12 de Novembro de 2017
 * 09h01min27s BRST
 */

public interface ReverseOperations {
	String reverse(String phrase);

} // interface ReverseOperations
